### ISSUE TITLE
Custom Theme, useContext types don't work.

### ISSUE THREAD

**Issue by ardeaf** [react-native-elements/react-native-elements#2168]
Tried to use a hook instead of the ThemeConsumer render props method to get my theme in my component, [as done here](https://github.com/react-native-elements/react-native-elements/pull/1894#issuecomment-494019019),  but TSLint throws an error:

```
import React, { useContext } from 'react';
import { Colors, Text, Theme, ThemeContext, ThemeProvider, } from 'react-native-elements';
import { View } from 'react-native';

interface MyTheme extends Theme {
  colors: {
    backgroundColor: string;
  } & Partial<Colors>;
}

const theme: MyTheme = {
  colors: {
    backgroundColor: 'pink',
  },
};

const App = () => {
  return (
    <ThemeProvider theme={theme}>
      <View>
        <TestComponent/>
      </View>
    </ThemeProvider>
  );
};

const TestComponent = () => {
  const { theme: customTheme } = useContext(ThemeContext);
  return <Text style={{ color: customTheme && customTheme.colors && customTheme.colors.backgroundColor }}>
    Open up App.js to start working on your app!
  </Text>;

};
```

This throws a type error:
`TS2339: Property 'backgroundColor' does not exist on type 'RecursivePartial<Colors>'`

**Comment by iRoachie** [comment]
Assuming a theme:

```js
const MyTheme = {
  colors: {
    backgroundColor: 'pink',
  },
};
```

### Current Problem
The typing for ThemeContext sets the theme to `{}` - https://github.com/react-native-elements/react-native-elements/blob/master/src/index.d.ts#L2069. So that's why you get an error because the `colors` attribute can't merge with `{}`.

The ideal situation in TS would've been to pass the generic through `useContext` into `ThemeProps<T>`. However, it seems there's no way to do this right now.

```tsx
// Would love to be able to do this

const Dreams = () => {
  const { theme } = useContext<typeof MyTheme>(ThemeContext);

  return <Text style={{ color: theme.colors.backgroundColor }}>Yep</Text>;
};
```

### Workaround

Instead, you'll have to cast the `useContext` call until the above is possible or we release a custom hook such as `useTheme` that will handle this automatically.

```tsx
const Reality = () => {
  const { theme } = useContext(ThemeContext) as ThemeProps<typeof MyTheme>;

  return <Text style={{ color: theme.colors.backgroundColor }}>Yep</Text>;
};
```

**Comment by ardeaf** [comment]
Ah makes sense. I'll go with the casting, which isn't too bad of a compromise.

**Comment by iRoachie** [comment]
> The MyTheme was already a type, so I didn't need to do typeof.

This is so you don’t have to make an interface as well as a literal. In your example if you update one then you’ll have to update the other. Using typeof means there’s only one source of truth
