### ISSUE TITLE
Feature Request for a DateTimePicker

### ISSUE THREAD

**Issue by pau-riosa** [react-native-elements/react-native-elements#2329]
**Is your feature request related to a problem? Please Describe.**
the whole package is very useful, except for a datetimepicker. there are a lot of packages who offer datetimepicker but not maintained. 

**Describe the solution you'd like**
Is it possible to create a datetimepicker for react-native-elements? I think it would be a powerful add-on since date, times and datetimes are necessary.

**Describe alternatives you've considered**
as I mentioned, some libraries are not maintained anymore.

**Additional context**

**Comment by pranshuchittora** [comment]
IMO one of the efficient methods of Date Time input is to use the platform defaults because of the user's familiarity with the platform. Having an iOS-like Date Time picker on Android might confuse the user. Apart from that, I think we first focus on making the core more robust and stable. 

@pau-riosa  I recommend that you use https://github.com/react-native-community/datetimepicker 

@flyingcircle IMO we shouldn't integrate such in RNE because that's not the first-class UI component/atom.

**Comment by flyingcircle** [comment]
I agree @pranshuchittora
