### ISSUE TITLE
Card image style

### ISSUE THREAD

**Issue by thefreeleo** [react-native-elements/react-native-elements#2350]
Bug

![image](https://user-images.githubusercontent.com/13882054/81377074-53009f80-9137-11ea-9f47-3d747057a75d.png)

Fix

![image](https://user-images.githubusercontent.com/13882054/81377119-6a3f8d00-9137-11ea-8240-5d8c253e515d.png)

**Comment by AugustinVoiMa** [comment]
Hello, 
I had been stuck with this warning since yesterday, the workaround was to supply style in imageProps when calling Card Component overriding default style: 
`<Card title="my card" image={...}   imageProps={{ style: {{width: null, height: 150}} }}> ... </Card>`

This solution may help to make this warning disappear but I imagine this need to be fixed in Card component definition as you said. 

PS: Since I am new to React Native and didn't found detailed documentation, I may have misunderstood some usages of this component so I'm still open to any better solution avoiding changes in framework's code

**Comment by flyingcircle** [comment]
@thefreeleo please submit a PR with this change

**Comment by flyingcircle** [comment]
This was fixed in 2.0.1
