### ISSUE TITLE
Button raised prop doesn't affect buttons in iOS

### ISSUE THREAD

**Issue by kas** [react-native-elements/react-native-elements#2363]
**Explain what you did**

I created a new React Native project with the React Native CLI (React Native 0.62.2). Then I installed React Native Elements 2.0.0. Then I created this root function component:

```
const App = () => {
return (
    <View>
      <Button raised title='Test' />
    </View>
  );
};
```

**Expected behavior**

I expected the button to appear raised in iOS. The button appears raised in Android (I can see the shadow below the button in Android).

**Describe the bug**

The button doesn't appear raised in iOS.

**To Reproduce**

See "Explain what you did" section above.

**Screenshots**

![image](https://user-images.githubusercontent.com/7661552/82172056-feb79700-987d-11ea-8bf1-aa5913956ba7.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |2.0.0|
| react-native          |0.62.2|

**Comment by superguineapig** [comment]
Just ran into this myself.

I think the culprit is https://github.com/react-native-elements/react-native-elements/blob/45b49524e83f104b3e46e1c0bdcc1eb46c45085c/src/buttons/Button.js#L222 which sets the default/internal buttonContainer view style.

If I had to guess, the code starting at line 254 of Button.js should add an overflow property like this:

```javascript
raised: type =>
    type !== 'clear' && {
      backgroundColor: '#fff',
      overflow: 'visible', // <-- here
      .
      .
      .
```

A workaround that worked for me is to explicitly add the overflow to the 'containerStyle' prop of your Button component, like this:

```
<Button containerStyle={{ overflow: 'visible' }} raised title='Test' />
```
