### ISSUE TITLE
Social Icon for Google dosen't follow Brand Guidelines

### ISSUE THREAD

**Issue by enigmablue** [react-native-elements/react-native-elements#2525]
The socialicon for type='google', shows an orange background, or orange text. I also can't find a way to put any icon that has the right color of the required icon color.

Unfortunately it does not suit/match the google brand guidelines.  https://developers.google.com/identity/branding-guidelines
Anyone noticed that?

**Comment by flyingcircle** [comment]
I'm not sure what you can do to change this? This is based on using the `Icon` class which is based on `react-native-vector-icons`. To my knowledge, it's not possible to create this button through this method. If you want to use the official google sign-in button, I suggest using this package: https://github.com/react-native-community/google-signin

**Comment by enigmablue** [comment]
Well, that's kind of besides the point (to use the other packages) because the whole purpose of the socialicon component (i believe) is meant to be able to support a consistent look. I also have others like apple, wechat, so they all look different if i try to use the default packages.

I couldn't use the apple one as well because it failed the brand guidelines, and the apple review rejected my build.  :(

So i had to remove this and revert back to my old way.

**Comment by enigmablue** [comment]
Can the SocialIcon use an Image that we have locally?

**Comment by flyingcircle** [comment]
`SocialIcon` isn't currently setup to handle an `Image`. It's really as simple as an svg with a preset color. The pattern that's there now might have been meant for google+. But since that's gone the way of the dinosaur, it might be obsolete. Google sign-in has a uniquely complicated button which is why I would suggest using the other package to make sure that you can follow their strict guidelines. Most other branding guidelines are pretty simple single color patterns. I don't see any preset 'apple' in `SocialIcon` at the moment, but it looks like it should be pretty simple. font-awesome provides an apple icon: https://fontawesome.com/icons/apple so you should be able to meet the guidelines with that icon on a white or block background.

**Comment by enigmablue** [comment]
thanks. but for apple: because my background is white, and to follow my other buttons (eg google) it needed a way to have a border around the whole component. i tried to add a border to the style but it seems like it didnt' work :/

So anyway I reverted to a non socialicon way to do this. Thanks though.

![image](https://user-images.githubusercontent.com/35584085/91626216-d2b0c380-e9df-11ea-962d-7c3f7d4a9751.png)

The one I am going for in Apple's guidelines

![image](https://user-images.githubusercontent.com/35584085/91626258-fd028100-e9df-11ea-986c-67f816bccead.png)
