### ISSUE TITLE
Header Text Alignment - IOS

### ISSUE THREAD

**Issue by natalyayyad** [react-native-elements/react-native-elements#2704]
I'm using the Header component, on Android its centered. However, On IOS seems like there's a top padding which I didn't add.
![image](https://user-images.githubusercontent.com/47296228/102147643-be4fe400-3e73-11eb-9837-166e0a7c5fd0.png)
![image](https://user-images.githubusercontent.com/47296228/102147680-cdcf2d00-3e73-11eb-91c4-995fb817f0aa.png)

code:
` <Header
        centerComponent={{
          text:'Header',
          style: {
            color: Theme.COLORS.TEXT,
            fontWeight: 'bold',
            fontSize: Theme.FONT.BIG,
          },
        }}
        containerStyle={{
          backgroundColor: Theme.COLORS.SECONDARY,
        }}
      />`

**Comment by pranshuchittora** [comment]
Can you provide a snack demo to reproduce the same

**Comment by natalyayyad** [comment]
Yes, here is the link:
[https://snack.expo.io/@natalyayyad/header-react-native-elements](url)

**Comment by pranshuchittora** [comment]
Hi @natalyayyad thanks for the demo. I am able to repro this.
Raised the PR for the fix :)

**Comment by flyingcircle** [comment]
I'm not sure that the issue is iOS here. You put the `Header` inside of a `SafeAreaView` component which is only applicable on iOS. If you put the `Header` outside of the `SafeAreaView`. I'll stick the rest of my comments in the PR.

**Comment by natalyayyad** [comment]
@pranshuchittora Thank you. @flyingcircle  I tried removing SafeAreaView, or replace it with View but the issue remains. 
What's the default height of the header seems like it's 60, right?

**Comment by otech47** [comment]
this is happening because the SafeAreaView is forced on all of the inner left/center/right `<Children>` components here: https://github.com/react-native-elements/react-native-elements/blob/next/packages/base/src/Header/Header.tsx#L149

would be nice to be able to pass down props to override the `edges` and `style` props on that inner container. it is just inside of the `containerStyle` so tweaking that doesn't help

![Screenshot 2023-03-09 at 2 16 49 PM](https://user-images.githubusercontent.com/4914611/224131192-1d218aa1-e172-446c-99d1-5cb1a369c93b.png)

**Comment by otech47** [comment]
actually it seems like the ability to customize those props will soon be in an upcoming release: https://github.com/react-native-elements/react-native-elements/pull/3741
