### ISSUE TITLE
Ref error

### ISSUE THREAD

**Issue by kevinveiga** [react-native-elements/react-native-elements#2866]
**I tried to use a "ref" in the Input component**

**do not show error of not having the type**

**Starting with version 3.3.1, the input component using a ref property, shows this error:

"Property 'ref' does not exist on type 'IntrinsicAttributes & Omit<TextInputProps..."**

**When normally using the Input component with the ref property**

[Screenshot](https://drive.google.com/file/d/1o0VQEp9fIhlEGQa2TIHqSNxQMXOk11K-/view?usp=sharing)

**Linux, VS Code:**

| software              | version |
| --------------------- | ------- |
| react-native-elements |3.3.1 or 3.3.2|
| react-native          |0.64.0|

**Comment by infothien** [comment]
I am also facing the same problem with SearchBar, so please give it a check
Also before I could use SearchBar as a type for useRef: `useRef<SearchBar|null>(null)` so that I could use sth like: 
```
searchRef.current?.clear()
```

But now, I cannot do that anymore so how should I deal with type for ref ?
<img width="388" alt="SearchBarCA_tsx_—_circleapp_frontend" src="https://user-images.githubusercontent.com/30365498/111410519-3b615280-871c-11eb-8aa8-3a14b8206d10.png">

Note: `react-native-elements: 3.2.0 worked well for me`

**Comment by khushal87** [comment]
You need to import SearchbarProps and pass it as `{...(searchBarProps as SearchbarProps)}`  to this Component where `searchBarProps` is simply a object `const searchBarProps = {};` This will solve the issue, I think its most probably a tsc warning. Thanks, feel free to ask and let me know if it doesn't work. @kevinveiga @infothien

**Comment by infothien** [comment]
Thank you for you comment @khushal87, I dont think it make sense too me since it is issues with TS of RNE. I think you got the fixes for that, so I might wait a bit and check later !

**Comment by pranshuchittora** [comment]
I am not able to repro this in the `next` branch code.
![Screenshot from 2021-04-03 17-31-42](https://user-images.githubusercontent.com/32242596/113477839-7c8a8e00-94a2-11eb-8167-211a29862a56.png)

And I am able to call `reff.current.focus()` without any error.
This will be released in the next release cycle
Feel free to reopen this.
