### ISSUE TITLE
Android autofill does not work on input component

### ISSUE THREAD

**Issue by hsavit1** [react-native-elements/react-native-elements#2998]
Android password autofill, with all of the required autofill props, does not work with the Input compoennt

**Expected behavior (Required)**

Comparing using Input vs using a standard react native TextInput, I was unable to get password autofill to work using the Input 

**Describe the bug (Required)**

**To Reproduce (Required)**
This will not work with android autofill
```

import { Input } from "react-native-elements"

                            <Input
                                placeholder="Password"
                                textContentType="password"
                                importantForAutofill="yes"
                                onChangeText={handleChange("password")}
                                autoCompleteType="password"
                                value={values?.password}
                                secureTextEntry={!showPassword}
                                accessible
                                accessibilityLabel="Password input"
                                accessibilityHint="Password Input"
                            />

```

This will work with android autofill
```

import { TextInput } from "react-native"

                            <TextInput
                                placeholder="Password"
                                textContentType="password"
                                importantForAutofill="yes"
                                onChangeText={handleChange("password")}
                                autoCompleteType="password"
                                value={values?.password}
                                secureTextEntry={!showPassword}
                                accessible
                                accessibilityLabel="Password input"
                                accessibilityHint="Password Input"
                            />

```

**Screenshots (Required)**

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         3.4|
| react-native          |         0.63.4|

**Comment by arpitBhalla** [comment]
@flyingcircle Duplicate #3067

**Comment by caricbrown** [comment]
I have seen this issue as well. <TextInput /> from 'react-native' autofill works great on Android, but <Input /> from 'react-native-elements' does not. However it might be due to the fact that we all use 'react-navigation' and thus 'react-native-screens'.

See: https://github.com/software-mansion/react-native-screens/issues/349

I can confirm that if you use state to control the render of the <Input /> then autofill will work more reliably but not 100% of the time.

I created a custom hook for my purposes but it would be great to understand why this happens at all with this library component.

`
import { useEffect, useState } from 'react'
import { Platform } from 'react-native'

export const useAutoFillHack = () => {
  /** THIS IS A TERRIBLE HACK TO MAKE AUTOFILL WORK ON ANDROID!!! */
  const [autoFill, setAutoFill] = useState()

  useEffect(() => {
    setAutoFill(true)
  }, [])

  return Platform.select({
    android: autoFill,
    ios: true
  })
}
`

then in your `screen`

if (!autoFill) return <></>
return (<Input .../>)
