### ISSUE TITLE
ListItem.Swipeable onSwipe method?

### ISSUE THREAD

**Issue by nica0012** [react-native-elements/react-native-elements#3179]
Hi, the team is doing a great job with improving RNE, bravo!

I have implemented the swipable functionality with the list item component but I may be missing something in the docs - are there any methods like onSwipe, onSwipeBegin, onSwipeEnd?

I am trying to disable scrolling on my Flatlist when the swipable is being swiped (I am doing this with another package I am hoping to replace completely)

Cheers.

**Comment by t1gor** [comment]
As far as I can tell from the [source code](https://github.com/react-native-elements/react-native-elements/blob/next/src/ListItem/ListItem.Swipeable.tsx#L14-L38), you only have `onLeftSwipe` and `onRightSwipe `

**Comment by nica0012** [comment]
@t1gor thanks for the reply! Good idea to look into the source code - I assumed this would work as expected (this is exactly what I was looking for) but those two methods do not seem to work. I am using the latest version too.

**Comment by arpitBhalla** [comment]
> but those two methods do not seem to work.
That code isn't released yet

**Comment by nica0012** [comment]
> > but those two methods do not seem to work.
> 
> That code isn't released yet

Ah that'll do it! thanks for the shout - any idea as to when the team is looking to release this? Cheers.

**Comment by arpitBhalla** [comment]
@nica0012  How `onSwipe` would be different from `onSwipeBegin`?

**Comment by nica0012** [comment]
It would be the same, onSwipeBegin would actually be better. The reason I need to detect this is because I want to disable the flatlist from scrolling vertically when the listItem is being swiped to avoid buggy behaviour. This is what I am doing with my previous package, "react-native-swipeable-row" which I am looking to get rid of once this method comes into play.

**Comment by dobeerman** [comment]
Hi there,

Any updates? ;)

**Comment by gtwilliams03** [comment]
I am watching this issue as well.  I am finding that the `ListItem.Swipeable` component is great for what I am doing (ScrollView with ListItems which can be scrolled vertically, but also swiped right and left to expose control buttons.  I do find that the vertical scrolling is quite difficult when using the `Swipeable` elements, because you pretty much have to scroll exactly vertically or it wants to swipe right or left.  The other issue is that, since I am exposing buttons on each of the left and right content areas, it would be nice to be able to programmatically return the `ListItem.Swipeable` to the neutral/closed position.  Right now, the users have to swipe to expose the buttons, press a button, and then swipe the element closed again, which is a less desirable user experience.

**Comment by arpitBhalla** [comment]
@dobeerman make sense to me, Would work on it once v4-beta.1 released
