### ISSUE TITLE
Conditional rendering Tab.Item / TabView.Item

### ISSUE THREAD

**Issue by felixliu226** [react-native-elements/react-native-elements#3390]
**Is your feature request related to a problem? Please Describe.**

I'm using the tab inside a screen, I need to hide a certain tab item based on some condition. When inside the <Tab> and I render the <Tab.Item> conditionally, it will pop up an error saying that React.cloneElement(...): The argument must be a React element, but you passed null.

I hope the Tab.Item could support the conditional rendering. Thx.

My code is like: 
```
<Tab>
    <Tab.Item title="item1" />]
    {condition && <Tab.Item title="item2" />}
    <Tab.Item title="item3" />
</Tab>
```

**Describe the solution you'd like**

The tab item / tab view item can be conditionally rendered.

**Describe alternatives you've considered**

I have to based on the condition to render different <Tab> component, which needs to duplicate a lot of codes.

**Additional context**

**Comment by WVAviator** [comment]
I did some quick research - this is happening because React.Children.map() traverses null values. From what I've read calling React.Children.toArray() will omit null values. So I think we can do that first instead and just map over the resulting array.

I'm happy to take a stab at it if you can assign me. Thanks!

**Comment by arpitBhalla** [comment]
Yep @WVAviator go for it.

**Comment by WVAviator** [comment]
So switching from using React.Children.map() to React.Children.toArray().map() in both Tab and TabView, as well as using .length on that array versus the other use of React.Children.count in TabView definitely works as far as resolving this issue - however depending on how this might be used it might not have the desired behavior. For example, if the developer wants the number of tabs to dynamically change _while_ the component is mounted, it's going to cause the user's active tab to switch since the currentIndex does not update.

I would expect the desired behavior to be for the user to remain on their current tab when other tabs are added or removed. This means conditional logic based on whether their current tab has an index that is greater than or less than the index of the tab that was removed in order to shift their new currentIndex appropriately. Going to see if I can implement this.
