### ISSUE TITLE
@react-native-elements(4.0.0-rc.0) is not available on yarn

### ISSUE THREAD

**Issue by leikoilja** [react-native-elements/react-native-elements#3399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain what you did

Run `yarn add @react-native-elements/base @react-native-elements/themed`

### Expected behavior

Installation works

### Describe the bug

Documentation at https://reactnativeelements.com/docs/migration_guide says to migrate using:
```js
yarn add @react-native-elements/base @react-native-elements/themed
```

while the command returns:
```bash
yarn add @react-native-elements/base
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-elements%2fbase: Not found".
info If you think this is a bug, please open a bug report with the information provided in ".../yarn-error.log".
```

Also can't find anything at `yarn` https://yarnpkg.com/package/@react-native-elements

### Steps To Reproduce

```markdown
Run `yarn add @react-native-elements/base @react-native-elements/themed`
```

### Your Environment

```markdown
yarn v1.22.17
```

**Comment by arpitBhalla** [comment]
You need to add .npmrc, refer installation guide

```tsx
@react-native-elements:registry=https://npm.pkg.github.com

```

**Comment by arpitBhalla** [comment]
Added this in migration guide too.

**Comment by shadowfish07** [comment]
@arpitBhalla Hi,expo EAS can't build 4.0.0-rc.0 because we need to firstly run npm login,but I don't know how to do it with expo EAS.Is there a way to install @react-native-elements(4.0.0-rc.0) without login?

I have tried `yarn add @react-native-elements/base@react-native-elements/react-native-elements#base` but I met error when run gradlew:
`
> Task :app:checkReleaseAarMetadata
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
Fast - Scalable - Integrated
[stderr] error node_modules/@react-native-elements/base/node_modules/color/index.js: Unexpected token: name (_28) in file node_modules/@react-native-elements/base/node_modules/color/index.js at 255:33.
Error: Unexpected token: name (_28) in file node_modules/@react-native-elements/base/node_modules/color/index.js at 255:33
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:279:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:146:24)
    at _next (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:168:9)
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:175:7
    at new Promise (<anonymous>)
    at /home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:164:12
    at minifyCode (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:289:17)
    at Object.<anonymous> (/home/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:569:40)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 2m 51s
`

I don't know if `yarn add @react-native-elements/base@react-native-elements/react-native-elements#base` is causing this problem...

**Comment by arpitBhalla** [comment]
@shadowfish07  Try doing 

```bash
# @react-native-elements/base
yarn add react-native-elements/react-native-elements#4.0.0-rc.0-base

# @react-native-elements/themed
yarn add react-native-elements/react-native-elements#4.0.0-rc.0-themed
```

**Comment by shadowfish07** [comment]
> @shadowfish07 Try doing
> 
> ```shell
> # @react-native-elements/base
> yarn add react-native-elements/react-native-elements#4.0.0-rc.0-base
> 
> # @react-native-elements/themed
> yarn add react-native-elements/react-native-elements#4.0.0-rc.0-themed
> ```

Thank you ! It works! And I can successfully build!

**Comment by shadowfish07** [comment]
> > @shadowfish07 Try doing
> > ```shell
> > # @react-native-elements/base
> > yarn add react-native-elements/react-native-elements#4.0.0-rc.0-base
> > 
> > # @react-native-elements/themed
> > yarn add react-native-elements/react-native-elements#4.0.0-rc.0-themed
> > ```
> 
> Thank you ! It works! And I can successfully build!

I run `eas build --platform android`,it successfully build.
And then I run `expo publish`,the same error occurs.
And then  I run `eas build --platform android` ,the same error occurs.

I'm new to React Native.It is really confusing...

**Comment by arpitBhalla** [comment]
Try removing lock file/node_modules, as `eas`  builds on cloud and `expo publish` build then push to AWS
